import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: "Spots - Hello App Router",
	description: 'Generated by create next app',
}

export default function spotsLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<div>{children}</div>
	)
}
