import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html>
			<body>

				<header className='w-full mx-auto px-4 lg:width-lg lg:px-0'>

					<div className='flex justify-between items-center py-2'>

						<Link href="/" className='text-4xl font-light'>Hello Next AppRouter</Link>

						<div className='flex gap-8'>
							<Link href="/" className='hover:underline'>Top</Link>
							<Link href="/about" className='hover:underline'>About</Link>
						</div>
					</div>
				</header>

				<div>{children}</div>
			</body>
		</html>
	)
}
